### PR TITLE
uses I18n.t for day_names and such

### PR DESCRIPTION
**Pull request by patleb**

### CODE REVIEW

**Comment by colavitam** [comment]
Looks good to me! Thanks for the pull request!

**Comment by dapicester** [comment]
Any plan for a new release of the gem including this PR?

**Comment by colavitam** [comment]
Yes, I'm hoping to get a new release up in the next week or two.

**Comment by colavitam** [comment]
Just released 0.0.2 with a few other changes. Let me know if you run into any problems!

**Pull request merged**
